name: personality_prediction_engine
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - pyarrow
  - tqdm
  - datasets            # Hugging Face loader (optional)
  - nltk                # VADER sentiment
  - spacy               # tokenization
  - sentence-transformers  # MiniLM embeddings
  - bertopic            # topic modeling
  - umap-learn          # for BERTopic dim-reduction
  - hdbscan             # for BERTopic clustering
  - scikit-learn        # RandomForest, PCA, etc.
  - optuna              # hyperparameter tuning
  - shap                # interpretability
  - flask               # Week 6 demo
  - streamlit           # Week 6 demo
  - flake8              # linting
  - mypy                # static type checks
  - pip
  - pip:
      - lexicalrichness
      - emoji
      - tsfresh>=0.21.0      # optional time-series features
